### ISSUE TITLE
Update to 1.0.128 not possible

### ISSUE THREAD

**Issue by Nastras** [kbrashears5/homebridge-schedule#106]
Hello, I just wanted to install the update to 1.0.128. Unfortunately this is not possible. It aborts the installation with the following errors.

![D09D90EB-361A-4F36-8ED3-67D09B3E4536](https://user-images.githubusercontent.com/27686185/119928781-8dc0ba00-bf7c-11eb-8466-8288f7eb5a9a.jpeg)

**Comment by ghost** [comment]
#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @kbrashears5 to notify them. This will be looked at soon!

**Comment by mbierman** [comment]
Fails for me too. 

**Environment:**

* **Node.js Version**: 14.16.0
* **NPM Version**: 6.14.11
* **Homebridge Version**: 1.3.4
* **Homebridge Config UI X Version**: v4.41.1
* **Operating System**: Docker
* **Process Supervisor**: Docker 
* **Alpine Linux**:3.12.4

**Comment by kbrashears5** [comment]
looks like i didn't understand how the `postinstall` was supposed to work. i'll get a fix going, since i unintentionally broke all my other packages as well...

**Comment by kbrashears5** [comment]
1.0.129 fixes this

**Comment by mbierman** [comment]
Seems good to me. Thank you!

**Comment by Nastras** [comment]
Thx!
