### ISSUE TITLE
Just updated and can’t load homebridge....

### ISSUE THREAD

**Issue by mbierman** [kbrashears5/homebridge-schedule#23]
1. Install latest build of this plugin.
1. Reboot homebridge.

**Result**
Homebridge cant load. See Below.

Restore previous version, 1.0.23
Homebridge is fine.  

Module | Version
-- | --
Node.js | 12.18.3
NPM | 6.14.7
homebridge | 1.1.1
Alpine Linux (running in a Docker on a Synology) | 3.12.0
homebridge-config-ui-x | v4.24
Homebridge-schedule | v1.0.28

![2857172D-34B3-40F3-AE67-1CC503B47018](https://user-images.githubusercontent.com/1205471/88447269-43176400-cde6-11ea-9faa-321388e69361.png)

**Comment by kbrashears5** [comment]
@mbierman apologies, was messing with my build stuff and messed that up. should be fixed now in v1.0.29

**Comment by mbierman** [comment]
Thanks!
