### ISSUE TITLE
Feature request: schedule sync

### ISSUE THREAD

**Issue by rogers-jp** [kbrashears5/homebridge-schedule#67]
Hi there. I really love this plugin and it is an simple, elegant and powerful way to automate a plethora of home devices. However, the schedule starting when the homebridge is booted is, I feel, a weakness. Sitting and waiting to reboot homebridge at a particular time defeats the point of automation. Is there a way that perhaps an optional setting could be added to the plugin such that if the dummy switch is manually actuated in HomeKit (eg toggled on and off within 10 seconds) or triggered by a daily shortcut, the timer is reset so it can be synced with other shortcuts and services? Thanks!

**Comment by ghost** [comment]
#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @kbrashears5 to notify them of the issue. This will be looked at soon!

**Comment by kbrashears5** [comment]
Have you tried out the cron options? I think that might get you what you need...

**Comment by rogers-jp** [comment]
Thanks for your reply. You make a good point, I'm sorry I didn't spot that. That certainly sorts the scheduling at a specific time I was looking for. With regards to syncing with other HomeKit triggers and shortcuts, I was wondering whether alongside the primary dummy switch, a secondary dummy switch (or a manual actuation of the primary) that resets the schedule timer might provide a hook for any HomeKit device or shortcut to establish sync. 
As a hypothetical example to show what I'm suggesting, let's say I have a device than I want to activate every 90 minutes for a work break throughout the day after I turn on my desk lamp in the morning. Your plug-in is perfect for that. But I could start work anywhere between 8:30 and 9:30. So I want the trigger of the lamp turning on to restart the timer on the 90-minute interval switch I've set up so I'm undisturbed for a full 90 minutes before the first instance. All the conditionality is dealt with by HomeKit and shortcuts, the schedule plugin just needs an automated way to trigger a 'phase-shift'.
As far as I can work out, correct me if I'm wrong, this isn't something that the plugin can currently do (without writing additional scripts to modify the scheduler cron options in response to events handled by different Homebridge plugins, which I'm not yet knowledgable enough to do - hence the feature suggestion!) Please understand that although I think this would be a really useful feature, the situation I described is just a hypothetical example so if what I'm suggesting is unworkable then don't worry about it. Thanks again for your time!

**Comment by ghost** [comment]
#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @kbrashears5 to notify them of the issue. This will be looked at soon!

**Comment by kbrashears5** [comment]
@rogers-jp hey - sorry for the (very) late response.

I think your use case could be accomplished by using my `homebridge-schedule` in coordination with `homebridge-dummy`. You'd be able to setup a dummy switch that basically does nothing.

Once you have that dummy switch, create a HomeKit automation something like 'When dummy switch turns on, turn on schedule switch'. The schedule switch in `homebridge-schedule` will turn itself off after 1 second, and also reset the timer, thus creating your 'reset schedule' button

**Comment by rogers-jp** [comment]
Sorry for the delay, thanks for your help with this. 🙂
