### ISSUE TITLE
Last update (1.0.93) error

### ISSUE THREAD

**Issue by miquellaboria** [kbrashears5/homebridge-schedule#74]
After update the plug-in show an error an remove all accessories and automations from the plug-in.

![6A10D29F-75C2-4927-A0D1-2325B138B605](https://user-images.githubusercontent.com/1266767/109389204-cf08e580-790b-11eb-9a8e-3c6c2ef67d7d.jpeg)

Restoring the previous versions works fine

**Comment by kbrashears5** [comment]
@miquellaboria I wasn't able to reproduce that specific error, but I was able to reproduce the accessories getting removed.

Let me know if 1.0.94 fixes it for you, it's working now for me.

**Comment by miquellaboria** [comment]
The 1.0.94 fixed the problem! Thanks!
