### ISSUE TITLE
Cron job generator

### ISSUE THREAD

**Issue by Nastras** [kbrashears5/homebridge-schedule#80]
Hello @kbrashears5, 
i just tested your plugin and I think it's really good. Thanks for your work! I wanted to recommend you to add a link to the cron job generator 
https://www.generateit.net/cron-job/ 
in your plugin description.

There you can easily create a string .-)

**Comment by ghost** [comment]
#### AUTOMATICALLY GENERATED by kbrashears5/github-action-issue-notifier

Mentioning @kbrashears5 to notify them of the issue. This will be looked at soon!

**Comment by kbrashears5** [comment]
@Nastras thanks for the comment.

I already have a link in the [readme](https://github.com/kbrashears5/homebridge-schedule/blob/master/README.md) to the package that I use for cron - they have documentation and for what they support there since cron strings can be different per package
